server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        # REST Client -> http://localhost:4000/api/patients
        # API Gateway -> http://patient-service:4000/patients
        # Patient Service -> /patients -> Patients Array
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1

        # REST Client -> http://localhost:4000/api-docs/patients
        # API Gateway -> http://patient-service:4000/v3/api-docs
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs
